### ISSUE TITLE
[Suggestion]: Make crafting recipes for sponges less op

### ISSUE THREAD

**Issue by mpustovoi** [Fuzss/permanentsponges#1]
### Suggestion (Required)

I like this mod because of the big QoL improvement it gives. The problem is the extreme ease of creating these permanent sponges.
To do this, you don't even need to go to the ocean monument to get an ordinary sponge, it would seem, the basis for crafting, because it's enough to get a spawnpoint near the swamp biome, find a couple of sheep and slimes there, and voila, already get an aquatic sponge. Moreover, the magmatic sponge is so op that it should require at least a nether star for crafting each, I guess.
Since I don't know how to edit the recipe from mod by myself and, of course, I could just delete this mod, but I really enjoy this and your other mods.
I hope for your understanding.

**Comment by Fuzss** [comment]
I'm aware that this mod is not inline with how difficult it normally is to obtain sponges in vanilla. The mod is intended for a modded experience though, where I'd imagine it shouldn't be necessary to put in too much effort for a minor technical utility. From that point of view I think the recipe is fine. You can still change the recipe with a datapack for your own playthrough.

**Comment by mpustovoi** [comment]
I understand you. Btw, I've already done that with a datapack.
